
function write_pydic( filename, train_conf, test_conf )

if train_conf.isbalanced 
    trainFile = sprintf('%strain_fall_balanced_%d_%d_%d_%d.%s', ...
        train_conf.out_datapath, train_conf.imwidth, train_conf.win, ...
        train_conf.stride, size(train_conf.data, 1), 'dat');
else
    trainFile = sprintf('%strain_fall_%d_%d_%d_%d.%s', ...
        train_conf.out_datapath, train_conf.imwidth, train_conf.win, ...
        train_conf.stride, size(train_conf.data, 1), 'dat');
end

train_conf.out_datapath = trainFile;

if ~isempty(test_conf.data)
    testFile = sprintf('%stest_imgs_%d_%d_%d_%d_f.%s', test_conf.out_datapath, ...
        train_conf.imwidth, test_conf.win, test_conf.stride, ...
        size(test_conf.data, 1), 'dat');
else
     testFile = "";
end

test_conf.out_datapath = testFile;

dict_format=['{\n\t"train_filename":"%s",', ...
              '\n\t"test_filename":"%s",' ...
              '\n\t"imdim":%d,' ...
              '\n\t"train_num_imgs":%d,' ... 
              '\n\t"test_num_imgs":%d,' ...
              '\n\t"train_num_samples":%d,' ...
              '\n\t"test_num_samples":%d,' ...
              '\n\t"train_stride":%d,' ...
              '\n\t"test_stride":%d,' ...
              '\n\t"train_isbalanced":%d,' ...
              '\n\t"test_isbalanced":%d' ...
              '\n}\n']; 

          
pydict = sprintf(dict_format, train_conf.out_datapath,    ...
                    test_conf.out_datapath,     ... 
                    train_conf.imwidth,     ...
                    size(train_conf.data, 1),    ...
                     size(test_conf.data, 1),    ...
                     train_conf.win,      ...
                     test_conf.win,      ...
                     train_conf.stride,          ...
                     test_conf.stride,           ...
                     train_conf.isbalanced,          ...
                     test_conf.isbalanced );
   
fid = fopen(filename,'w');
fprintf(fid, pydict);
fclose(fid);

traindata = train_conf.data;
save(train_conf.out_datapath, 'traindata');

if ~isempty(test_conf.data)
    testdata = test_conf.data;
    save(test_conf.out_datapath, 'testdata');
end
 
end

